"""八卦、五行、天干地支、纳甲、六亲等基础数据 (基于 liu-yao 实现)"""

from enum import IntEnum
from dataclasses import dataclass, field


# ═══════════════════════════════════════════════════════════════
# 爻 (Yao Enum)
# ═══════════════════════════════════════════════════════════════

class Yao(IntEnum):
    LAO_YIN = 0    # 老阴 (0 heads, 3 tails) → 变爻 (阴→阳)
    SHAO_YANG = 1  # 少阳 (1 head, 2 tails)  → 静爻 (阳)
    SHAO_YIN = 2   # 少阴 (2 heads, 1 tail)  → 静爻 (阴)
    LAO_YANG = 3   # 老阳 (3 heads, 0 tails) → 变爻 (阳→阴)

    @property
    def is_changing(self) -> bool:
        return self in (Yao.LAO_YIN, Yao.LAO_YANG)

    @property
    def yin_yang(self) -> str:
        """返回本卦中的阴阳"""
        return "阳" if self in (Yao.SHAO_YANG, Yao.LAO_YANG) else "阴"

    @property
    def line_code(self) -> str:
        """1=阳, 2=阴 用于构建卦码"""
        return "1" if self in (Yao.SHAO_YANG, Yao.LAO_YANG) else "2"

    @property
    def changing_line_code(self) -> str:
        """变卦中该爻的阴阳"""
        return "2" if self in (Yao.SHAO_YANG, Yao.LAO_YANG) else "1"

    @property
    def display(self) -> str:
        return {Yao.LAO_YIN: "老阴 ⚋⚋", Yao.SHAO_YANG: "少阳 ⚊",
                Yao.SHAO_YIN: "少阴 ⚋", Yao.LAO_YANG: "老阳 ⚊⚊"}[self]


# ═══════════════════════════════════════════════════════════════
# 五行 (WuXing)
# ═══════════════════════════════════════════════════════════════

@dataclass
class WuXingData:
    name: str
    sheng: str = ""   # 我生 (generates)
    ke: str = ""      # 我克 (controls)
    bei_sheng: str = ""  # 生我 (is generated by)
    bei_ke: str = ""     # 克我 (is controlled by)

    def __post_init__(self):
        _WX_MAP = {
            "金": ("水", "木", "土", "火"),
            "木": ("火", "土", "水", "金"),
            "水": ("木", "火", "金", "土"),
            "火": ("土", "金", "木", "水"),
            "土": ("金", "水", "火", "木"),
        }
        if self.name in _WX_MAP:
            self.sheng, self.ke, self.bei_sheng, self.bei_ke = _WX_MAP[self.name]


WU_XING = {
    name: WuXingData(name)
    for name in ["金", "木", "水", "火", "土"]
}

# 五行生克关系
SHENG_RELATION = {wx: WU_XING[wx].sheng for wx in WU_XING}  # 生
KE_RELATION = {wx: WU_XING[wx].ke for wx in WU_XING}          # 克


# ═══════════════════════════════════════════════════════════════
# 天干 (TianGan) - 10 Heavenly Stems
# ═══════════════════════════════════════════════════════════════

TIAN_GAN = {
    "甲": "木", "乙": "木", "丙": "火", "丁": "火", "戊": "土",
    "己": "土", "庚": "金", "辛": "金", "壬": "水", "癸": "水",
}


# ═══════════════════════════════════════════════════════════════
# 地支 (DiZhi) - 12 Earthly Branches
# ═══════════════════════════════════════════════════════════════

DI_ZHI = {
    "子": "水", "丑": "土", "寅": "木", "卯": "木",
    "辰": "土", "巳": "火", "午": "火", "未": "土",
    "申": "金", "酉": "金", "戌": "土", "亥": "水",
}

DI_ZHI_ORDER = list(DI_ZHI.keys())


# ═══════════════════════════════════════════════════════════════
# 八卦 (BaGua) - 8 Trigrams
# ═══════════════════════════════════════════════════════════════

@dataclass
class BaGuaData:
    name: str           # 卦名
    element: str        # 自然元素: 天地山泽水火风雷
    wuxing: str         # 五行归属
    xiantian: int       # 先天数 1-8
    direction: str      # 方位
    chu_yao: int = 1    # 初爻 (1=阳, 2=阴)
    er_yao: int = 1     # 二爻
    shan_yao: int = 1   # 三爻(上爻)
    body_part: str = ""  # 人体部位
    animal: str = ""     # 动物
    symbol: str = ""     # 符号

    @property
    def code(self) -> str:
        return f"{self.chu_yao}{self.er_yao}{self.shan_yao}"


BA_GUA: dict[str, BaGuaData] = {
    "乾": BaGuaData("乾", "天", "金", 1, "西北", 1, 1, 1, "首", "马", "☰"),
    "兑": BaGuaData("兑", "泽", "金", 2, "西",   1, 1, 2, "口", "羊", "☱"),
    "离": BaGuaData("离", "火", "火", 3, "南",   1, 2, 1, "目", "雉", "☲"),
    "震": BaGuaData("震", "雷", "木", 4, "东",   1, 2, 2, "足", "龙", "☳"),
    "巽": BaGuaData("巽", "风", "木", 5, "东南", 2, 1, 1, "股", "鸡", "☴"),
    "坎": BaGuaData("坎", "水", "水", 6, "北",   2, 1, 2, "耳", "豕", "☵"),
    "艮": BaGuaData("艮", "山", "土", 7, "东北", 2, 2, 1, "手", "狗", "☶"),
    "坤": BaGuaData("坤", "地", "土", 8, "西南", 2, 2, 2, "腹", "牛", "☷"),
}

BA_GUA_BY_XIANTIAN = {v.xiantian: v for v in BA_GUA.values()}
BA_GUA_BY_CODE = {v.code: v for v in BA_GUA.values()}


# ═══════════════════════════════════════════════════════════════
# 纳甲 (NaJia) - 六爻纳干支系统
# ═══════════════════════════════════════════════════════════════

# 每卦3爻的干支纳配 (内卦/外卦)
# 格式: [(天干, 地支), ...] 从下到上

NA_JIA = {
    "乾": {
        "inner": [("甲", "子"), ("甲", "寅"), ("甲", "辰")],
        "outer": [("壬", "午"), ("壬", "申"), ("壬", "戌")],
    },
    "坎": {
        "inner": [("戊", "寅"), ("戊", "辰"), ("戊", "午")],
        "outer": [("戊", "申"), ("戊", "戌"), ("戊", "子")],
    },
    "震": {
        "inner": [("庚", "子"), ("庚", "寅"), ("庚", "辰")],
        "outer": [("庚", "午"), ("庚", "申"), ("庚", "戌")],
    },
    "艮": {
        "inner": [("丙", "辰"), ("丙", "午"), ("丙", "申")],
        "outer": [("丙", "戌"), ("丙", "子"), ("丙", "寅")],
    },
    "坤": {
        "inner": [("乙", "未"), ("乙", "巳"), ("乙", "卯")],
        "outer": [("癸", "丑"), ("癸", "亥"), ("癸", "酉")],
    },
    "巽": {
        "inner": [("辛", "丑"), ("辛", "亥"), ("辛", "酉")],
        "outer": [("辛", "未"), ("辛", "巳"), ("辛", "卯")],
    },
    "离": {
        "inner": [("己", "卯"), ("己", "丑"), ("己", "亥")],
        "outer": [("己", "酉"), ("己", "未"), ("己", "巳")],
    },
    "兑": {
        "inner": [("丁", "巳"), ("丁", "卯"), ("丁", "丑")],
        "outer": [("丁", "亥"), ("丁", "酉"), ("丁", "未")],
    },
}


def get_najia_for_hexagram(xia_gua_name: str, shang_gua_name: str) -> list[dict]:
    """获取重卦的纳甲信息，返回6爻的干支列表 (从初爻到上爻)"""
    xia = NA_JIA.get(xia_gua_name, {})
    shang = NA_JIA.get(shang_gua_name, {})
    lines = []
    for tg, dz in (xia.get("inner", []) + shang.get("outer", [])):
        lines.append({"tiangan": tg, "dizhi": dz, "wuxing": DI_ZHI.get(dz, "")})
    return lines


# ═══════════════════════════════════════════════════════════════
# 六亲 (Six Relations) - 基于五行生克
# ═══════════════════════════════════════════════════════════════

def get_liuqin(gua_wuxing: str, yao_dizhi: str) -> str:
    """
    根据卦宫五行和爻的地支五行确定六亲关系
    以卦宫五行为「我」
    - 生我者父母, 我生者子孙
    - 克我者官鬼, 我克者妻财
    - 同我者兄弟
    """
    yao_wx = DI_ZHI.get(yao_dizhi, "")
    if not yao_wx or not gua_wuxing:
        return ""

    if yao_wx == gua_wuxing:
        return "兄弟"
    if WU_XING[yao_wx].sheng == gua_wuxing:
        return "父母"
    if WU_XING[yao_wx].ke == gua_wuxing:
        return "妻财"
    if WU_XING[yao_wx].bei_sheng == gua_wuxing:
        return "子孙"
    if WU_XING[yao_wx].bei_ke == gua_wuxing:
        return "官鬼"
    return ""


def get_liuqin_for_lines(gua_wuxing: str, najia_lines: list[dict]) -> list[str]:
    """获取六爻的六亲关系"""
    return [get_liuqin(gua_wuxing, line["dizhi"]) for line in najia_lines]


# ═══════════════════════════════════════════════════════════════
# 体用生克分析
# ═══════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════
# 六爻股票预测分析 (财爻 + 世应 + 六亲生克)
# ═══════════════════════════════════════════════════════════════

def analyze_stock_divination(
    gong_wuxing: str, liuqin: list[str], najia_lines: list[dict],
    shi_yao: int, ying_yao: int, changing_lines: list[int],
    tiyong: dict,
) -> dict:
    """
    综合六爻股票预测分析
    核心: 妻财爻代表股价，妻财旺则涨，妻财弱则跌
    """
    analysis_parts = []
    bullish_signals = 0
    bearish_signals = 0

    # 1. 找到妻财爻位置
    cai_yao_positions = [i + 1 for i, q in enumerate(liuqin) if q == "妻财"]
    zi_sun_positions = [i + 1 for i, q in enumerate(liuqin) if q == "子孙"]
    xiong_di_positions = [i + 1 for i, q in enumerate(liuqin) if q == "兄弟"]
    guan_gui_positions = [i + 1 for i, q in enumerate(liuqin) if q == "官鬼"]
    fu_mu_positions = [i + 1 for i, q in enumerate(liuqin) if q == "父母"]

    # 2. 财爻分析
    if cai_yao_positions:
        for pos in cai_yao_positions:
            idx = pos - 1
            cai_wx = najia_lines[idx]["wuxing"] if idx < len(najia_lines) else ""

            # 旺衰: 得宫位五行生助 = 旺，被克 = 衰
            if cai_wx and gong_wuxing:
                if WU_XING[gong_wuxing].sheng == cai_wx:
                    bullish_signals += 2
                    analysis_parts.append(f"财爻在第{pos}爻({cai_wx})，得宫位{gong_wuxing}所生，财星旺相，主股价有上涨动力")
                elif WU_XING[gong_wuxing].ke == cai_wx:
                    bearish_signals += 2
                    analysis_parts.append(f"财爻在第{pos}爻({cai_wx})，被宫位{gong_wuxing}所克，财星受制，主股价承压")
                elif gong_wuxing == cai_wx:
                    bullish_signals += 1
                    analysis_parts.append(f"财爻在第{pos}爻({cai_wx})，与宫位比和，财星平稳")
                elif cai_wx == WU_XING[gong_wuxing].sheng:
                    bearish_signals += 1
                    analysis_parts.append(f"财爻在第{pos}爻({cai_wx})，生宫位而泄气，财星偏弱")

            # 财爻是否为动爻
            if pos in changing_lines:
                bullish_signals += 1
                analysis_parts.append(f"财爻在第{pos}爻发动，财运有变化之机，若化进神则大涨")

            # 财爻是否持世
            if pos == shi_yao:
                bullish_signals += 2
                analysis_parts.append(f"财爻持世(第{pos}爻)，财来就我，大吉之象，预示得财获利")
    else:
        analysis_parts.append("卦中无财爻，财星不现，需看伏神或变卦中是否有财")
        bearish_signals += 1

    # 3. 世应分析
    shi_liuqin = liuqin[shi_yao - 1] if 0 < shi_yao <= len(liuqin) else ""
    ying_liuqin = liuqin[ying_yao - 1] if 0 < ying_yao <= len(liuqin) else ""
    shi_wx = najia_lines[shi_yao - 1]["wuxing"] if 0 < shi_yao <= len(najia_lines) else ""
    ying_wx = najia_lines[ying_yao - 1]["wuxing"] if 0 < ying_yao <= len(najia_lines) else ""

    analysis_parts.append(f"世爻在第{shi_yao}爻({shi_liuqin})，代表问卦者自身")
    analysis_parts.append(f"应爻在第{ying_yao}爻({ying_liuqin})，代表所问之事(股市)")

    # 世应生克
    if shi_wx and ying_wx:
        if WU_XING[shi_wx].ke == ying_wx:
            bullish_signals += 1
            analysis_parts.append(f"世克应({shi_wx}克{ying_wx})，我制事体，利于主动操作，看涨")
        elif WU_XING[ying_wx].ke == shi_wx:
            bearish_signals += 2
            analysis_parts.append(f"应克世({ying_wx}克{shi_wx})，事体制我，市场不利于己，看跌")
        elif WU_XING[shi_wx].sheng == ying_wx:
            bearish_signals += 1
            analysis_parts.append(f"世生应，泄自身之气，需谨慎")
        elif WU_XING[ying_wx].sheng == shi_wx:
            bullish_signals += 1
            analysis_parts.append(f"应生世，市场有利，收益可期")

    # 4. 子孙爻分析 (生财爻)
    if zi_sun_positions:
        for pos in zi_sun_positions:
            if pos in changing_lines:
                bullish_signals += 1
                analysis_parts.append(f"子孙爻在第{pos}爻发动，子孙生财，财源旺盛，利好上涨")

    # 5. 兄弟爻分析 (克财爻)
    if xiong_di_positions:
        for pos in xiong_di_positions:
            if pos in changing_lines:
                bearish_signals += 2
                analysis_parts.append(f"兄弟爻在第{pos}爻发动，兄弟劫财，主破财下跌，需警惕")

    # 6. 综合判断
    net = bullish_signals - bearish_signals
    if net >= 3:
        overall = "看涨"
        overall_desc = "财爻得力，多方信号明显，股价上涨概率较大"
    elif net >= 1:
        overall = "偏涨"
        overall_desc = "多方略占优势，但需结合体用生克综合判断"
    elif net >= -1:
        overall = "震荡"
        overall_desc = "多空力量均衡，股价可能横盘整理"
    elif net >= -3:
        overall = "偏跌"
        overall_desc = "空方略占优势，需防范下跌风险"
    else:
        overall = "看跌"
        overall_desc = "财爻受制，空方信号明显，股价下跌概率较大"

    # 7. 结合体用
    ti_sentiment = tiyong.get("sentiment", "")
    if ti_sentiment == "bullish":
        if overall in ("偏跌", "看跌"):
            overall_desc += "。但体用生克偏多，需权衡"
    elif ti_sentiment == "bearish":
        if overall in ("偏涨", "看涨"):
            overall_desc += "。但体用生克偏空，需权衡"

    return {
        "cai_yao_positions": cai_yao_positions,
        "zi_sun_positions": zi_sun_positions,
        "xiong_di_positions": xiong_di_positions,
        "shi_liuqin": shi_liuqin,
        "ying_liuqin": ying_liuqin,
        "bullish_signals": bullish_signals,
        "bearish_signals": bearish_signals,
        "net_score": net,
        "overall": overall,
        "overall_desc": overall_desc,
        "analysis": analysis_parts,
    }


def analyze_tiyong(xia_gua: BaGuaData, shang_gua: BaGuaData, changing_lines: list[int]) -> dict:
    """体用生克分析: 体卦(下卦/内卦)为自身, 用卦(上卦/外卦)为事体"""
    ti_wx = xia_gua.wuxing  # 体卦五行
    yong_wx = shang_gua.wuxing  # 用卦五行

    if ti_wx == yong_wx:
        relation = "比和"
        desc = "体用比和，诸事顺遂，股价平稳偏涨"
    elif WU_XING[yong_wx].sheng == ti_wx:
        relation = "用生体"
        desc = "用卦生体卦，大吉之象，有外力相助，股价看涨"
    elif WU_XING[ti_wx].sheng == yong_wx:
        relation = "体生用"
        desc = "体卦生用卦，泄气之象，有消耗之意，股价可能承压"
    elif WU_XING[ti_wx].ke == yong_wx:
        relation = "体克用"
        desc = "体卦克用卦，虽克为吉但需费力，小幅看涨"
    elif WU_XING[yong_wx].ke == ti_wx:
        relation = "用克体"
        desc = "用卦克体卦，大凶之象，外力压制，股价看跌"
    else:
        relation = "未知"
        desc = "需综合判断"

    return {
        "ti_gua": xia_gua.name,
        "ti_wuxing": ti_wx,
        "yong_gua": shang_gua.name,
        "yong_wuxing": yong_wx,
        "relation": relation,
        "description": desc,
        "sentiment": "bullish" if relation in ("用生体", "体克用", "比和") else "bearish",
    }
